Repository yiisoft/form-model, pull requests merged in 2024-08, with the labels that each got.

#48 Adapt to Yii Validator 2
  composer.json
  src/Field.php
  src/FieldFactory.php
  src/FormModelInputData.php
  tests/FieldFactoryTest.php
  tests/FieldTest.php
  tests/FormModelTest.php
Labels: status:code review

#49 Update hydrator version
  composer.json
Labels: dependencies

#45 Docs, form model
  README.md
  docs/guide/en/README.md
  docs/guide/en/form-model.md
  docs/guide/en/nested-form-models.md
Labels: status:code review, type:docs

#51 Fix double validation
  composer.json
  config/di.php
  src/FormHydrator.php
  src/FormModel.php
  src/FormModelInterface.php
  src/ValidatedInputInterface.php
  tests/FormHydratorTest.php
  tests/FormModelTest.php
  tests/Support/TestHelper.php
Labels: status:code review, type:bug, type:feature

#52 Docs, form hydrator
  docs/guide/en/form-hydrator.md
  src/FormHydrator.php
Labels: status:code review, type:docs

#54 Refactor validation rules enricher
  src/ValidationRulesEnricher.php
Labels: status:code review, type:task

#55 Docs, hydrator extensions
  docs/guide/en/form-hydrator.md
Labels: status:code review, type:docs

#53 Docs: input data, pure fields and validation rules enricher
  docs/guide/en/README.md
  docs/guide/en/displaying-fields.md
  docs/guide/en/form-model-input-data.md
  docs/guide/en/form-model.md
  docs/guide/en/validation-rules-enricher.md
Labels: status:code review, type:docs

#58 Remove `ValidatedInputInterface`
  src/FormModelInterface.php
  src/ValidatedInputInterface.php
Labels: status:code review, type:task

#56 Fill general usage section in readme
  README.md
Labels: status:code review, type:docs

#64 Add `Label` attribute support
  README.md
  src/FormModel.php
  tests/FormModelTest.php
  tests/Support/Form/LabelForm.php
Labels: status:code review

#65 Add `Hint` and `Placeholder` attributes
  README.md
  docs/guide/en/form-model.md
  src/Attribute/Hint.php
  src/Attribute/Placeholder.php
  src/Attribute/Safe.php
  src/FormModel.php
  tests/FormModelTest.php
  tests/SafeTest.php
  tests/Support/Form/AttributeForm.php
  tests/Support/Form/FormWithNestedStructures.php
  tests/Support/Form/LabelForm.php
  tests/Support/Form/LoginForm.php
  tests/Support/Form/NestedRuleForm/MainForm.php
Labels: status:code review, type:feature

#66 Cleanup
  README.md
  composer.json
  src/Attribute/Hint.php
  src/Attribute/Placeholder.php
  src/FormModelInterface.php
  src/NonArrayTypeCaster.php
Labels: status:code review
